<?php
include 'func.php';
$t=getdate();
echo "<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <link href='log.css' media='screen' rel='Stylesheet' type='text/css' />\n";
echo "  </head>\n";
echo "  <body>\n";
echo "    <div class='main'>\n";
echo "      <div class='item'>\n";
echo "        <form action='addit.php' method='post'>\n";
echo "          <table>\n";
echo "            <thead>\n";
echo "              <tr><th colspan='2'>New Entry</th></tr>\n";
echo "            </thead>\n";
echo "            <tfoot>\n";
echo "                <tr><th colspan='2'><input type='submit' value='Add' /></th></tr>\n";
echo "            </tfoot>\n";
echo "            <tbody class='every'>\n";
echo "              <tr>\n";
echo "                <td>n<br /><input type='text' name='n' value='N3163B' /></td>\n";
echo "                <td>make<br /><input type='text' name='make' value='C170B' /></td>\n";
echo "              </tr>\n";
echo "              <tr>\n";
echo "                <td>".date_select('mm-dd-yyyy',$t['mon'],$t['mday'],$t['year'])."</td>\n";
echo "                <td>to-from<br /><input type='text' name='fromto' /></td>\n";
echo "              </tr>\n";
echo "              <tr>\n";
echo "                <td colspan=2>\n";
echo "                  NoInstrApp <input type='text' name='NoInstrApp' value='0' size='2' />\n";
echo "                  Holds      <input type='text' name='holds'      value='0' size='2' />\n";
echo "                  Track      <input type='text' name='track'      value='0' size='2' />\n";
echo "                </td>\n";
echo "              </tr>\n";
echo "              <tr>\n";
echo "                <td>dlnds<br /><input type='text' name='dlnds' value='0' /></td>\n";
echo "                <td>nlnds<br /><input type='text' name='nlnds' value='0' /></td>\n";
echo "              </tr>\n";
echo "              <tr>\n";
echo "                <td>sel<br />  <input type='text' name='sel'   value='0.0' /></td>\n";
echo "                <td>xcoun<br /><input type='text' name='xcoun' value='0.0' /></td>\n";
echo "              </tr>\n";
echo "              <tr>\n";
echo "                <td>day<br />  <input type='text' name='day'   value='0.0' /></td>\n";
echo "                <td>night<br /><input type='text' name='night' value='0.0' /></td>\n";
echo "              </tr>\n";
echo "              <tr>\n";
echo "                <td>pic<br /> <input type='text' name='pic'  value='0.0' /></td>\n";
echo "                <td>dual<br /><input type='text' name='dual' value='0.0' /></td>\n";
echo "              </tr>\n";
echo "              <tr>\n";
echo "                <td>total<br /><input type='text' name='total' value='0.0' /></td>\n";
echo "                <td>s_ins<br /><input type='text' name='s_ins' value='0.0' /></td>\n";
echo "              </tr>\n";
echo "              <tr>\n";
echo "                <td>comments<br /><input type='text' name='comments' /></td>\n";
echo "                <td>cfi<br /><input type='text' name='cfi' /></td>\n";
echo "              </tr>\n";
echo "            </tbody>\n";
echo "          </table>\n";
echo "        </form>\n";
echo "      </div>\n";
echo "      <div class='item'>\n";
echo "        <a href='list.php'>Back to list</a>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  </body>\n";
echo "</html>\n";
?>
